resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: Khazinawaz/pipelines_run_1
      branches:
        include: ^tests-failing$
      gitProvider: nawaz_gh

  # - name: matrix_property_bag_in
  #   type: PropertyBag
  #   configuration:
  #     key1: value1
  #     key2: value2

  # - name: matrix_property_bag_out
  #   type: PropertyBag
  #   configuration:
  #     key1: value1

  # - name: incoming
  #   type: IncomingWebhook
  #   configuration:
  #     webhookName: incoming

pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          # integrations:
          #   - name: gen
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/failing
            - add_pipeline_files saveTests/failing pipelines_state
            - add_run_files saveTests/failing run_state
            - echo "Passed"
            # - echo "$int_gen_K"
            - popd

  #     - name: Matrix_Fan_Out_1
  #       type: FanOut
  #       configuration:
  #         integrations:
  #           - name: gen
  #         inputSteps: 
  #           - name: Normal_Step      
  #       execution: 
  #         onExecute:
  #           - echo "I am on fan out step"
  #           - touch fan_out.txt
  #           - set_step_var fan_out value1
  #           - echo "Fan out working" > fan_out_1.txt
  #           - echo "$int_gen_K"

  #     - name: matrix_2
  #       type: Matrix
  #       stepMode: Bash
  #       configuration:
  #         integrations:
  #           - name: gen
  #         inputSteps: 
  #           - name: Matrix_Fan_Out_1
  #         inputResources:
  #           - name: self_repo
  #           - name: matrix_property_bag_in
  #         outputResources:
  #           - name: matrix_property_bag_out
  #       stepletMultipliers:
  #         environmentVariables:
  #           - env1: one
  #             env2: two
  #             env3: three
  #           - env1: changed1
  #             env2: changed2
  #           - key_1: value1
  #             key_2: value2
  #           - key_1: value3
  #             key_2: value4
  #           - key_1: value5
  #             key_2: value6
  #         runtimes:
  #           - type: image
  #             image:
  #               auto:
  #                 language: cpp
  #                 versions:
  #                   - 8.0.0

  #       execution:
  #         onExecute:
  #           - echo "$int_gen_K"
  #           - echo "I am on matrix step"
  #           - ls -l ./Matrix_Fan_Out_1
  #           - touch ${steplet_id}_file
  #           - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
  #           - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
  #           - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
  #           - set_step_var test_key "$(date)"
  #           - set_step_var addresses "https://www.google.com/${env1}/${steplet_id}"
  #           - get_step_var Matrix_Fan_Out_1 fan_out
  #           - get_step_var Matrix_Fan_Out_2 fan_out
  #           - get_step_var Matrix_Fan_Out_3 fan_out
  #           - write_output matrix_property_bag_out "env1"="$env1"
  #           - pushd "$res_self_repo_resourcePath/"
  #           - save_tests saveTests/empty/temp
  #           - save_tests saveTests/correct
  #           - echo "Passed"
  #           - popd
  #           - ls -l .
      
  #     - name: Matrix_Fan_In
  #       type: FanIn
  #       configuration:
  #         integrations:
  #           - name: gen
  #         inputSteps: 
  #           - name: matrix_2
  #         outputResources:
  #           - name: incoming
  #       execution:
  #         onExecute:
  #           - echo "Hello World"
  #           - ls -l .
  #           - ls -l ./matrix_2
  #           - ls -l ./matrix_2/Matrix_Fan_Out_1/
  #           - echo "$int_gen_K"
  #           - get_step_var matrix_2 test_key
  #           - get_step_var matrix_2 addresses
  #           - export JFROG_CLI_BUILD_NUMBER=1234
  #           - export RELEASE_VERSION=1234
  #           - set_payload incoming "{ \"build_number\":\"$JFROG_CLI_BUILD_NUMBER\",   \"step_name\":\"$step_name\",  \"version\":\"$RELEASE_VERSION\" }" 
  
  # - name: Test_incoming_Webhook
  #   steps:
  #     - name: Test_incoming
  #       type: Bash
  #       configuration:
  #         inputResources:
  #           - name: incoming
  #       execution:
  #         onExecute:
  #           - echo "Hello from incoming"

          