pipelines:
  - name: Matrix_Demo_Env
    steps:
      - name: fanout_demo
        type: PreMatrix
        execution:
          onExecute:
            - echo "Executing fanout step...."
            - echo "File got created in fanout step" >> input.txt
      
      - name: fanout_demo_2
        type: PreMatrix
        execution:
          onExecute:
            - echo "Executing fanout step...."
            - echo "File got created in fanout step" >> input.txt

      - name: fanout_demo_3
        type: PreMatrix
        execution:
          onExecute:
            - echo "Executing fanout step...."
            - echo "File got created in fanout step" >> input.txt

      - name: matrix_demo
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: fanout_demo
            - name: fanout_demo_2
            - name: fanout_demo_3
        stepletMultipliers:
          environmentVariables:
            - key1: value1
              key2: value2
            - key1: value3
              key2: value4
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - cat ./fanout_demo/input.txt
            - cat ./fanout_demo_2/input.txt
            - cat ./fanout_demo_3/input.txt
            - touch input
            - cat ./fanout_demo/input.txt ./fanout_demo_2/input.txt ./fanout_demo_3/input.txt > input.txt
            - mkdir -p files
            - echo "-----"
            - echo "File got created in steplet ${steplet_number}" >> ./files/${steplet_number}.txt
            - echo "Running on runtime ${step_image_name}:${step_image_tag}" >> ./files/${steplet_number}.txt
            - echo "-----"
            - set_step_var matrix_envs "key1 = ${key1},key2 = ${key2}"



      - name: matrix_demo_2
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: fanout_demo
            - name: fanout_demo_2
            - name: fanout_demo_3
        stepletMultipliers:
          environmentVariables:
            - key1: value1
              key2: value2
            - key1: value3
              key2: value4
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - cat ./fanout_demo/input.txt
            - cat ./fanout_demo_2/input.txt
            - cat ./fanout_demo_3/input.txt
            - touch input
            - cat ./fanout_demo/input.txt ./fanout_demo_2/input.txt ./fanout_demo_3/input.txt > input.txt
            - mkdir -p files
            - echo "-----"
            - echo "File got created in steplet ${steplet_number}" >> ./files/${steplet_number}.txt
            - echo "Running on runtime ${step_image_name}:${step_image_tag}" >> ./files/${steplet_number}.txt
            - echo "-----"
            - set_step_var matrix_envs "key1 = ${key1},key2 = ${key2}"

      - name: fanin_demo
        type: PostMatrix
        configuration:
          inputSteps: 
            - name: matrix_demo
            - name: matrix_demo_2
        execution:
          onExecute:
            - echo "Executing fanin step"
            - echo "Matrix state files..."
            - ls -l matrix_demo/files/
            - ls -l matrix_demo_2/files
            - echo "state 1 files..."
            - cat matrix_demo/files/*
            - echo "state 2 files"
            - cat matrix_demo_1/files/*
            - ls -l matrix_demo/fanout_demo
            - get_step_var matrix_demo matrix_envs
            - get_step_var matrix_demo_2 matrix_envs


              