resources:
  - name: self_repo
    type: GitRepo
    configuration:
      path: vishnurao12/pipelines_run_1
      branches:
        include: ^tests-failing$
      gitProvider: git_v

  - name: matrix_property_bag_in
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: matrix_property_bag_out
    type: PropertyBag
    configuration:
      key1: value1

pipelines:
  - name: Pipeline
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution: 
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/failing
            - echo "Passed"
            - popd

      - name: Matrix_Fan_Out_1
        type: preMatrix
        configuration:
          inputSteps: 
            - name: Normal_Step      
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - set_step_var fan_out value1
            - echo "Fan out working" > fan_out_1.txt

      - name: matrix_2
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps: 
            - name: Matrix_Fan_Out_1
          inputResources:
            - name: self_repo
        stepletMultipliers:
          environmentVariables:
            - env1: one
              env2: two
              env3: three
            - env1: changed1
              env2: changed2
            - key_1: value1
              key_2: value2
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
        execution:
          onExecute:
            - echo "I am on matrix step"
            - ls -l ./Matrix_Fan_Out_1
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
            - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
            - set_step_var test_key "$(date)"
            - set_step_var addresses "https://www.google.com/${env1}/${steplet_id}"
            - get_step_var Matrix_Fan_Out_1 fan_out
            - pushd "$res_self_repo_resourcePath/"
            # - save_tests saveTests/empty/temp
            # - save_tests saveTests/correct
            # - echo "Passed"
            - popd
            - ls -l .
      
      - name: Matrix_Fan_In
        type: postMatrix
        configuration:
          inputSteps: 
            - name: matrix_2
        execution:
          onExecute:
            - echo "Hello World"
            - ls -l .
            - ls -l ./matrix_2
            - ls -l ./matrix_2/Matrix_Fan_Out_1/
            - get_step_var matrix_2 test_key
            - get_step_var matrix_2 addresses
 
